## = Data Source
## ==============================================================
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/studentdb?createDatabaseIfNotExist=true
#    username: root
#    password: 2323
#
#    # ==============================================================
#    # = Keep the connection alive if idle for a long time (needed in production)
#    # ==============================================================
#    test-while-idle: true
#    validation-query: SELECT 1
#
#  jpa:
#    # ==============================================================
#    # = Show or not log for each sql query
#    # ==============================================================
#    show-sql: true
#
#    # ==============================================================
#    # = Hibernate ddl auto (create, create-drop, update)
#    # ==============================================================
#    hibernate:
#      ddl-auto: update
#    generate-ddl: true
#
#    # ==============================================================
#    # = The SQL dialect makes Hibernate generate better SQL for the chosen database
#    # ==============================================================
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#
#
#  # ==============================================================
#  # = Initialize the database using data.sql script
#  # ==============================================================
#  sql:
#    init:
#      mode: always
